// <auto-generated />
using System;
using Dominio.Modelo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dominio.Migrations
{
    [DbContext(typeof(LibreriaContext))]
    [Migration("20240722004600_PrimerMigracion")]
    partial class PrimerMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dominio.Modelo.AuditoriaAutor", b =>
                {
                    b.Property<int>("IdAuditoriaAutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAuditoriaAutor"));

                    b.Property<int?>("AnoFal")
                        .HasColumnType("integer");

                    b.Property<int?>("AnoNac")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FkIdAutor")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdAuditoriaAutor");

                    b.ToTable("AuditoriaAutores");
                });

            modelBuilder.Entity("Dominio.Modelo.AuditoriaLibro", b =>
                {
                    b.Property<int>("IdAuditoriaLibro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAuditoriaLibro"));

                    b.Property<int?>("AnoPublicacion")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FkIdAutor")
                        .HasColumnType("integer");

                    b.Property<int?>("FkIdEstado")
                        .HasColumnType("integer");

                    b.Property<int?>("FkIdLibro")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdAuditoriaLibro");

                    b.ToTable("AuditoriaLibros");
                });

            modelBuilder.Entity("Dominio.Modelo.Autor", b =>
                {
                    b.Property<int>("IdAutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAutor"));

                    b.Property<int?>("AnoFal")
                        .HasColumnType("integer");

                    b.Property<int?>("AnoNac")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdAutor");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("Dominio.Modelo.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdEstado");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("Dominio.Modelo.Libro", b =>
                {
                    b.Property<int>("IdLibro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLibro"));

                    b.Property<int?>("AnoPublicacion")
                        .HasColumnType("integer");

                    b.Property<int?>("FkIdAutor")
                        .HasColumnType("integer");

                    b.Property<int?>("FkIdEstado")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdLibro");

                    b.HasIndex("FkIdAutor");

                    b.HasIndex("FkIdEstado");

                    b.ToTable("Libros");
                });

            modelBuilder.Entity("Dominio.Modelo.Libro", b =>
                {
                    b.HasOne("Dominio.Modelo.Autor", "Autor")
                        .WithMany()
                        .HasForeignKey("FkIdAutor");

                    b.HasOne("Dominio.Modelo.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("FkIdEstado");

                    b.Navigation("Autor");

                    b.Navigation("Estado");
                });
#pragma warning restore 612, 618
        }
    }
}
